## Tensor Operations:
A tensor is a multi-dimensional array, similar to a NumPy array.
In PyTorch, tensors can be created using the torch.Tensor class.
Basic tensor operations like addition, subtraction, multiplication, and division can be performed using the standard arithmetic operators +, -, *, /.
Here are some short exercises to help you get started:

### Exercise 1: Creating Tensors
Create a 2x3 tensor filled with zeros and a 3x2 tensor filled with ones using PyTorch. Print the tensors to verify that they are created correctly.

In [1]:
import torch
import torch.nn as nn

In [2]:
# Create a 2x3 tensor filled with zeros
zeros_tensor = torch.zeros(2, 3)
print(zeros_tensor)

# Create a 3x2 tensor filled with ones
ones_tensor = torch.ones(3, 2)
print(ones_tensor)

rand_tensor = torch.randint(0, 9, (4,6))
print(rand_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2, 6, 4, 4, 1, 3],
        [6, 0, 4, 1, 1, 7],
        [0, 5, 7, 8, 1, 5],
        [6, 7, 1, 3, 1, 3]])


### Exercise 2: Performing Basic Tensor Operations
Perform basic tensor operations using PyTorch. Create two tensors of the same shape and perform addition, subtraction, multiplication, and division.

In [3]:
# Create two tensors of the same shape
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# Perform addition
c = a + b
print(c)

# Perform subtraction
d = a - b
print(d)

# Perform multiplication
e = a * b
print(e)

# Perform division
f = a / b
print(f)


tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


## Automatic Differentiation:
- Learn about automatic differentiation, a key feature of PyTorch that makes it easy to compute gradients for optimization
- Understand the basics of backpropagation, which is used to train deep neural networks

## Building Neural Networks:
- Learn how to build neural networks using PyTorch's nn module
    - PyTorch's nn module makes it easy to construct and train neural networks. The basic idea is to define a neural network as a sequence of layers, where each layer performs a specific computation on the input data. PyTorch provides several types of layers, such as linear layers, convolutional layers, and recurrent layers, as well as various activation functions that can be used between the layers to introduce nonlinearity into the model.
    - A simple example of building a neural network with PyTorch's nn module might involve defining a network architecture with a few layers (e.g., fully connected layers, convolutional layers, etc.) and specifying the activation functions to use between each layer. Here's a basic example:
- Understand the different types of layers and activation functions used in neural networks

Example:

In [4]:
# Define a neural network with one hidden layer
class MyNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MyNet, self).__init__()
        self.hidden = nn.Linear(input_size, hidden_size)
        self.output = nn.Linear(hidden_size, output_size)
        
    def forward(self, x):
        x = torch.relu(self.hidden(x))
        x = self.output(x)
        return x

# Instantiate the neural network
net = MyNet(input_size=10, hidden_size=20, output_size=1)

# Apply the neural network to some input data
x = torch.randn(32, 10)
y = net(x)



In this example, we define a neural network with one hidden layer using PyTorch's nn module. The __init__ method initializes the layers of the network, and the forward method defines how the input data is transformed as it passes through the network. We also instantiate the neural network and apply it to some random input data.

Here are some exercises you can try to build your understanding of building neural networks in PyTorch:

1. Define a neural network with two hidden layers using the nn module.
- Use the ReLU activation function for the hidden layers and the sigmoid activation function for the output layer.
- Make the network input size 784 (for images in the MNIST dataset),
    - the first hidden layer size 256
    - the second hidden layer size 128
    - the output layer size 10 (for the 10 possible digit classes).

In [5]:
# Define a neural network with two hidden layers
class MyNet(nn.Module):
    def __init__(self):
        super(MyNet, self).__init__()
        self.hidden1 = nn.Linear(784, 256)
        self.hidden2 = nn.Linear(256, 128)
        self.output = nn.Linear(128, 10)

    #The forward method is called internally for the MyNet class by the __call__ method.
    def forward(self, x):
        x = torch.relu(self.hidden1(x))
        x = torch.relu(self.hidden2(x))
        x = torch.sigmoid(self.output(x))
        return x

# Instantiate the neural network
net = MyNet()

# Apply the neural network to some input data
x = torch.randn(32, 784)
y = net(x)

In [6]:
y

tensor([[0.4988, 0.4841, 0.4792, 0.5236, 0.4730, 0.5306, 0.5206, 0.5241, 0.5200,
         0.4922],
        [0.5019, 0.4898, 0.4670, 0.5216, 0.4418, 0.5075, 0.5114, 0.4935, 0.4842,
         0.5059],
        [0.5228, 0.4733, 0.4533, 0.4939, 0.4796, 0.5236, 0.4765, 0.5052, 0.5030,
         0.4994],
        [0.4871, 0.4741, 0.4725, 0.5020, 0.4317, 0.5002, 0.4670, 0.5020, 0.4989,
         0.4849],
        [0.4935, 0.4819, 0.4665, 0.4987, 0.4663, 0.4736, 0.5441, 0.5287, 0.4526,
         0.4820],
        [0.5296, 0.5170, 0.4890, 0.5054, 0.4644, 0.5075, 0.4922, 0.5117, 0.4817,
         0.4970],
        [0.4833, 0.5151, 0.4751, 0.4924, 0.4689, 0.5169, 0.5132, 0.5237, 0.4776,
         0.4885],
        [0.4987, 0.4947, 0.4921, 0.5055, 0.4634, 0.5072, 0.5100, 0.5302, 0.4868,
         0.4762],
        [0.5116, 0.4906, 0.4640, 0.5035, 0.4683, 0.5267, 0.5075, 0.4731, 0.5155,
         0.4875],
        [0.5169, 0.4787, 0.4783, 0.5018, 0.4987, 0.5185, 0.5126, 0.4989, 0.4947,
         0.4634],
        [0

2. Define a neural network with a convolutional layer followed by two fully connected layers using the nn module. 
- Use the ReLU activation function for the hidden layers and the softmax activation function for the output layer. 
- Make the convolutional layer have 10 output channels, a kernel size of 5, and a stride of 1. 
- Make the first fully connected layer have 100 output units and the second fully connected layer have 10 output units (for the 10 possible digit classes in MNIST).

## Training Neural Networks:
- Learn how to train a neural network using PyTorch's autograd and optim modules
- Understand the concepts of loss functions, optimization algorithms, and learning rates

## Data Loading:
- Learn how to load and preprocess data using PyTorch's DataLoader and transforms modules
- Understand how to prepare data for training and testing

## Model Evaluation:
- Learn how to evaluate the performance of a trained model on a test set
- Understand the concepts of accuracy, precision, and recall

## Advanced Topics:
- Learn about advanced topics:
    - convolutional neural networks
    - recurrent neural networks
    - transfer learning
- Understand how to use PyTorch for tasks:
    - image classification
    - natural language processing
    - reinforcement learning